### ISSUE TITLE
20190331社会心理学会议01

### ISSUE THREAD

**Issue by GarvinDon** [DcyWalker/SocialPsychology#2]
## 摘要 
1.人时地 
2.流水 
3.重点内容 
4.后续行动 

## 人时地 
与会人员：walker、开来超、慧贤 
记录人员：Adon 
时间：3.30 16:00-17:53 

## 流水 
```
**walker：** 
社会心理学
为什么选这个 

目标
不单单是全局认识，是能实践的，有助于生活的 
增加有趣度 
例如：通过社会事件，预测未来人们的行为 

**开来超：** 
先全局认识，通过某些关键字，再找一个落脚点 
可能的方向：育儿 

**慧贤：** 
社会心理学对于个人、群体 
个人：自我概念、理想自我、态度、问题归因、依恋关系 
群体：种族偏见、伦理、学派 

**walker：** 
可以参考上位词、下位词 
引起我关注的：生活方式、交往心理学、行为和行为机制 
需先根据万方的图谱，找到切入点，再做全局认识 

希望做到预测，找到规律，例如交往心理学，可以直接用于实践的 

事例 
老人认为小孩子会冷，所以尽量多穿衣服；而年轻一代，会学习科学育儿，适时给小孩子添减衣物 
老人认为小孩子吃手指会脏，造成流口水，所以包着小孩子的手，不给小孩子吃；而科学育儿表明，吃手是小孩子认知自己身体的表现，是无害的行为 
待探究：这是什么现象，背后有什么社会心理学 

**慧贤：** 
通过案例反映社会心理学理论 
两个人，有什么个人的心理？产生了什么行为？ 
三人（群体），有什么个人的心理、群体的心理？对大家的行为产生了什么影响 

**开来超：** 
心理学对人的行为的影响，是有规律可循的。我们可以找到规律，实现预测人的行为 
环境只会影响行为后的结果 

**大家：** 
切入点要小，有限时间内可完成 

**慧贤：** 
找到来切入 
某一个社会现象/日常会发生的事情但大家都不知道背后的心理学点 
能引起大家好奇，找到规律，活着一些反常识的知识 

**开来超：** 
规律、公式化、可实践 

**walker：** 
目标：做一个有趣的算命的罗盘 
一人做一个方向，每天进行汇报分享，再制定下一步的行动框架 
第二周时间比较紧急，需要整合资料、制作ppt 
```
## 重点内容
- 大致方向：做一个有趣的算命的罗盘 
	- 社会心理学范围很广泛，需要找一个足够细的、能实践的切入点，并且能引起人们兴趣和共鸣，找到人们忽略的规律
- 行动框架：一人做一个方向，每天进行汇报分享，再制定下一步的行动框架 

### 人员安排 

- walker 
	- 空闲时间：早上5-9、晚上7-12 
	- 选题：社会心理学——family，life style，paternalism，social valies

- 开来超 
	- 空闲时间：早上7-10、晚上7后 
	- 选题：社会心理学——行为和行为机制

- 慧贤 
	- 空闲时间：早上9前、晚上9后 
	- 选题：交往心理学 
	- 分享时间：周三晚上 

### 提交方式： 
日常简单交流：微信群
信息分析报告：重要信息提交到GitHub 

### 时间节点： 

- 最好2.5天一小总结分享 
- 每天都需要提交进度、情况 

## ChangeLog
190331 V1.0 Adon初稿
190401 V1.1 Walker补充

**Comment by DcyWalker** [comment]
@GarvinDon 好棒！！！
