### ISSUE TITLE
社会心理学项目第一阶段，开来超任务领取

### ISSUE THREAD

**Issue by DcyWalker** [DcyWalker/SocialPsychology#5]
社会心理学*上位术语* **行为和行为机制**

**Comment by nowherekai** [comment]
社会心理学的上位术语，它的下位术语有行为、态度、情绪、个性、社会心理学等

在万方中搜索“行为和行为机制”（心理学），内容比较杂乱，和社会心理学的关联没有太大。

用"Behavior and behavioral mechanisms", "Behavior  and behavioral mechanisms", "Behavior  and behavior mechanisms", "behavioral mechanisms", "behavior mechanism""搜索google scholar，也是内容太多，和心理学关系比较大，看不到和社会心理学太大的关系。

https://scholar.google.com/scholar?hl=en&as_sdt=0,5&q=Behavior+and+behavioral+mechanisms

https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=behavioral+mechanisms&btnG=

## Behaviorism(行为主义)
斯金纳的行为主义更多的属于心理学，研究的是单个人。

用"social psychology" AND "Behaviorism"搜索得到的是Behaviorism有关的结果

## 结论
行为和行为机制是社会心理学的上位词，不太容易和社会心理学直接挂钩，没有得到太多信息
