### ISSUE TITLE
“文化自觉”的阶梯综阅读总结

### ISSUE THREAD

**Issue by nowherekai** [DcyWalker/SocialPsychology#8]
## 简介
以杜瓦斯的解释水平为线索，当代统一的社会心理学，从最为微观和最为心 理学化的个体内过程到最为宏观和最为社会学化的群际过程，都有典范的主宰理论模型。
用解释水平这个框架，把心理学的主流理论做了一个分类工作。

## 解释水平作为概念框架对社会心理学的过程和研究主题（理论）进行分类

| 名称                                                       | 解释                                                         | 研究主题                                                     | 理论模型                                                     |
| ---------------------------------------------------------- | ------------------------------------------------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ |
| 个体内水平（the intra-personal or intra-individual level） | 最为微观也最为心理学化的解释水平，主要关注个体在社会情境中组织其 社会认知、社会情感和社会经验的机制，并不直接处理个体和社会环境之间的互动。 | 具身性（embodiment）、自我、社会知觉和归因、社会认知和文化认知、社会情感、社会态度等 | 认知失调论，态度形成和改变的双过程模型等                     |
| 人际和情景水平（the interpersonal and situational level）  | 在给定的情景中所发生的人际过程                               | 和亲密关系、竞争与合作等                                     | 社会比较论                                                   |
| 社会位置水平（the social positional level）                | 关注社 会行动者在社会位置中的跨情景差异（inter-situational differences） | 的影响和少数人的影响、权威服从、群体绩效、领导—部属关系等    | 少数人影响的皈依模型（conversion theory）、多数 人和少数人影响的双过程模型和社会表征论 |
| 意识形态水平（the ideological level）或群际水平            | ，关注或考虑研究参与者所携带 的信念、表征、评价和规范系统    | 感如偏见、群际行为如歧视及其应对和污名（stigma）             | 社会认同论，文化动态建构论                                   |
## 主宰范式
* 个体过程：社会认知范式
* 群体过程：社会表征范式
* 群际过程：社会认同范式

## 其他
态度形成和改变就是《影响力》的全部内容，可以介绍？
另外一本偏学术的是《态度改变与社会影响》
## 总结
把社会心理学的所有主流理论找到，并做分类，解释水平是一个貌似不错的框架，上面只列了一部分，还需要补充

## changelog
w5d3创建

**Comment by nowherekai** [comment]
@DcyWalker 把我们加到这个repository的Collaborators里面吧，这样我们也可以对项目做一些编辑，不然只能提issue。
owner和Collaborators的权限说明：
https://help.github.com/en/articles/permission-levels-for-a-user-account-repository

如何添加Collaborators：https://help.github.com/en/articles/inviting-collaborators-to-a-personal-repository

我和huixian的github username分别是：nowherekai、wangguoguo0130

**Comment by DcyWalker** [comment]
好的
